### ISSUE TITLE
感谢&&一起聊聊&&教教我吧

### ISSUE THREAD

**Issue by 1623275623** [SkecisAI/UE-ProgramBrowser#3]
大哥对你所做的工作真是仰慕至极啊，自己目前也在研究虚幻引擎开发独立应用程序的方向。希望作者能够早日开发出一个独立的程序出来，可以简化独立应用程序开发的流程。让更多人可以学习相关的内容。希望能有机会和作者共同讨论。在此郑重的感谢作者所做出的努力。

**Comment by SkecisAI** [comment]
言重了，都是参考了别人的想法，阅读UE的源码发掘的
